DECLARE @t NVARCHAR(128) =
  CASE
    WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'F_DOCENTETE') THEN 'F_DOCENTETE'
    WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'F_DOCENTET') THEN 'F_DOCENTET'
  END;

IF @t IS NULL
BEGIN
  PRINT 'ERREUR: Table F_DOCENTETE introuvable';
  SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' ORDER BY TABLE_NAME;
  RETURN;
END

PRINT 'Table: ' + @t;
DECLARE @sql NVARCHAR(MAX), @col NVARCHAR(128), @type NVARCHAR(50);
DECLARE cur CURSOR FOR
  SELECT v.col, v.typ FROM (VALUES
    ('SFEC_NUM_CERTIF',  'VARCHAR(50) NULL'),
    ('SFEC_NUM_CERTIF1', 'VARCHAR(50) NULL'),
    ('SFEC_NUM_CERTIF2', 'VARCHAR(69) NULL'),
    ('SFEC_SIGNATURE',   'VARCHAR(256) NULL'),
    ('SFEC_QR_CODE',     'VARCHAR(MAX) NULL'),
    ('SFEC_DATE_CERTIF',  'DATETIME NULL'),
    ('SFEC_DATE_CERTIF1', 'DATETIME NULL'),
    ('SFEC_STATUT',       'VARCHAR(20) NULL')
  ) v(col, typ);

OPEN cur;
FETCH NEXT FROM cur INTO @col, @type;
WHILE @@FETCH_STATUS = 0
BEGIN
  IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(@t) AND name = @col)
  BEGIN
    SET @sql = 'ALTER TABLE ' + QUOTENAME(@t) + ' ADD ' + QUOTENAME(@col) + ' ' + @type;
    EXEC(@sql);
    PRINT '  + ' + @col;
  END
  ELSE
    PRINT '  - ' + @col + ' (existe)';
  FETCH NEXT FROM cur INTO @col, @type;
END
CLOSE cur; DEALLOCATE cur;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_SFEC_STATUT' AND object_id = OBJECT_ID(@t))
BEGIN
  SET @sql = 'CREATE INDEX IX_SFEC_STATUT ON ' + QUOTENAME(@t) + '(SFEC_STATUT) WHERE SFEC_STATUT IS NOT NULL';
  EXEC(@sql);
  PRINT '  + Index SFEC_STATUT cree';
END

PRINT 'Termine.';